# Generated by Django 4.2.29 on 2026-03-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Записано')),
                ('period_from', models.DateTimeField(verbose_name='Период с')),
                ('period_to', models.DateTimeField(verbose_name='Период по')),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='Всего попыток')),
                ('successful_attempts', models.PositiveIntegerField(default=0, verbose_name='Успешных')),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='Неуспешных')),
                ('avg_recognition_confidence', models.FloatField(default=0.0, verbose_name='Ср. уверенность распознавания')),
                ('min_recognition_confidence', models.FloatField(default=0.0, verbose_name='Мин. уверенность распознавания')),
                ('max_recognition_confidence', models.FloatField(default=0.0, verbose_name='Макс. уверенность распознавания')),
                ('recognition_above_threshold', models.PositiveIntegerField(default=0, verbose_name='Выше порога распознавания')),
                ('avg_quality_score', models.FloatField(default=0.0, verbose_name='Ср. оценка качества')),
                ('min_quality_score', models.FloatField(default=0.0, verbose_name='Мин. оценка качества')),
                ('max_quality_score', models.FloatField(default=0.0, verbose_name='Макс. оценка качества')),
                ('quality_above_threshold', models.PositiveIntegerField(default=0, verbose_name='Выше порога качества')),
                ('liveness_available', models.BooleanField(default=False, verbose_name='Данные живости доступны')),
                ('avg_liveness_score', models.FloatField(blank=True, null=True, verbose_name='Ср. оценка живости')),
                ('fail_no_face_count', models.PositiveIntegerField(default=0, verbose_name='Лицо не обнаружено')),
                ('fail_quality_count', models.PositiveIntegerField(default=0, verbose_name='Низкое качество')),
                ('fail_recognition_count', models.PositiveIntegerField(default=0, verbose_name='Не распознан')),
            ],
            options={
                'verbose_name': 'Снимок метрик',
                'verbose_name_plural': 'Снимки метрик',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_threshold', models.FloatField(default=0.65, help_text='0.0–1.0. Минимальная схожесть для успешной аутентификации.', verbose_name='Порог распознавания')),
                ('quality_threshold', models.FloatField(default=0.35, help_text='0.0–1.0. Минимальное качество лица для обработки.', verbose_name='Порог качества изображения')),
                ('liveness_threshold', models.FloatField(default=0.7, help_text='0.0–1.0. Зарезервировано для детекции живости.', verbose_name='Порог живости (заглушка)')),
                ('max_auth_attempts', models.PositiveIntegerField(default=5, help_text='После превышения — блокировка аккаунта.', verbose_name='Макс. попыток входа')),
                ('lockout_minutes', models.PositiveIntegerField(default=15, verbose_name='Время блокировки (мин)')),
                ('liveness_enabled', models.BooleanField(default=False, help_text='Заглушка. Включить после интеграции модели.', verbose_name='Детекция живости включена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
