# Generated by Django 4.2.29 on 2026-04-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='use_webhook',
            field=models.BooleanField(default=False, help_text='Отправлять HTTP-запрос на URL вебхука при успешной идентификации у домофона.', verbose_name='Использовать вебхук'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='webhook_url',
            field=models.CharField(blank=True, default='http://localhost:5050/webhook/open', help_text='Эндпоинт, принимающий команду открытия двери.', max_length=500, verbose_name='URL вебхука'),
        ),
    ]
