# Generated by Django 4.2.29 on 2026-05-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0002_systemsettings_use_webhook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='use_webhook',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='webhook_url',
        ),
    ]
