# Generated by Django 4.2.29 on 2026-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0003_remove_systemsettings_use_webhook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='liveness_enabled',
            field=models.BooleanField(default=False, verbose_name='Обнаружение живости включена'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='liveness_threshold',
            field=models.FloatField(default=0.7, help_text='0.0–1.0.', verbose_name='Порог живости'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='max_auth_attempts',
            field=models.PositiveIntegerField(default=5, help_text='После превышения - блокировка аккаунта.', verbose_name='Макс. попыток входа'),
        ),
    ]
