# Generated by Django 4.2.29 on 2026-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0003_remove_systemsettings_use_webhook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmetricssnapshot',
            name='fail_liveness_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Liveness отказ'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='liveness_challenge_timeout',
            field=models.PositiveIntegerField(default=45, help_text='15–120. Максимальное время на выполнение активного задания.', verbose_name='Таймаут challenge (сек)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='liveness_identity_threshold',
            field=models.FloatField(default=0.52, help_text='0.3–0.9. Мин. косинусная схожесть во время challenge. Рекомендуется: 0.50–0.55.', verbose_name='Порог верификации личности (same-person)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='liveness_passive_accept',
            field=models.FloatField(default=0.68, help_text='0.5–0.95. Score выше — принять без challenge. Рекомендуется: 0.68.', verbose_name='Порог пассивного принятия'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='liveness_passive_reject',
            field=models.FloatField(default=0.22, help_text='0.05–0.49. Score ниже — жёсткий отказ. Рекомендуется: 0.22.', verbose_name='Порог пассивного отказа'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='liveness_enabled',
            field=models.BooleanField(default=False, help_text='Включить гибридную проверку живости (пассивная + активный challenge).', verbose_name='Детекция живости включена'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='liveness_threshold',
            field=models.FloatField(default=0.7, help_text='Зарезервировано. Используйте liveness_passive_accept / reject.', verbose_name='Порог живости (legacy)'),
        ),
    ]
