# Generated by Django 4.2.29 on 2026-05-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0004_modelmetricssnapshot_fail_liveness_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='liveness_threshold',
        ),
    ]
