# Generated by Django 4.2.29 on 2026-03-15 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('level', models.CharField(choices=[('INFO', 'Информация'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка')], default='INFO', max_length=10, verbose_name='Уровень')),
                ('component', models.CharField(max_length=100, verbose_name='Компонент')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Доп. данные')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Системный лог',
                'verbose_name_plural': 'Системные логи',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_username', models.CharField(blank=True, max_length=150, verbose_name='Введённый логин')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('result', models.CharField(choices=[('success', 'Успех'), ('fail_quality', 'Низкое качество изображения'), ('fail_no_face', 'Лицо не обнаружено'), ('fail_recognition', 'Лицо не распознано'), ('fail_liveness', 'Проверка живости не пройдена'), ('fail_locked', 'Аккаунт заблокирован')], max_length=30, verbose_name='Результат')),
                ('recognition_confidence', models.FloatField(default=0.0, verbose_name='Уверенность распознавания')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='Оценка качества')),
                ('liveness_score', models.FloatField(blank=True, null=True, verbose_name='Оценка живости (заглушка)')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал аутентификации',
                'verbose_name_plural': 'Журнал аутентификации',
                'ordering': ['-timestamp'],
            },
        ),
    ]
