# Generated by Django 4.2.29 on 2026-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationlog',
            name='failure_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
    ]
