# Generated by Django 4.2.29 on 2026-04-01 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biometric', '0002_alter_authenticationlog_failure_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('result', models.CharField(choices=[('granted', 'Доступ разрешён'), ('denied', 'Доступ запрещён'), ('no_face', 'Лицо не обнаружено')], max_length=20, verbose_name='Результат')),
                ('recognition_confidence', models.FloatField(default=0.0, verbose_name='Уверенность')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='Качество кадра')),
                ('door_opened', models.BooleanField(default=False, verbose_name='Дверь открыта')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP сервиса')),
                ('snapshot', models.ImageField(blank=True, upload_to='door_snapshots/', verbose_name='Снимок кадра')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к домофону',
                'verbose_name_plural': 'Доступ к домофону',
                'ordering': ['-timestamp'],
            },
        ),
    ]
