# Generated by Django 4.2.29 on 2026-05-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0003_dooraccesslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoorAccessLog',
        ),
    ]
